event_index:
    path:     /
    defaults: { _controller: "EventBundle:EventBlog:index" }
    methods:  GET

event_show:
    path:     /{id}/show
    defaults: { _controller: "EventBundle:EventBlog:show" }
    methods:  GET

event_new:
    path:     /new
    defaults: { _controller: "EventBundle:EventBlog:new" }
    methods:  [GET, POST]

event_edit:
    path:     /{id}/edit
    defaults: { _controller: "EventBundle:EventBlog:edit" }
    methods:  [GET, POST]

event_delete:
    path:     /{id}/delete
    defaults: { _controller: "EventBundle:EventBlog:delete" }
    methods:  DELETE
