<?php

namespace product\productBundle\Repository;

/**
 * categorie_PRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categorie_PRepository extends \Doctrine\ORM\EntityRepository
{
}
