
opinon_ajout:
    path:     /ajouto
    defaults: { _controller: OpinionBundle:Feedback:new }
opinion_aff:
    path:     /ajoutof
    defaults: { _controller: OpinionBundle:Feedback:show }
opinion_success:
    path:     /success
    defaults: { _controller: OpinionBundle:Feedback:Success }
stat:
    path:     /stat
    defaults: { _controller: OpinionBundle:Default:chart }
forum_opinion_delete:
    path:     /{id}/opiniondelete
    defaults: { _controller:  OpinionBundle:Feedback:deleteAdmin }
    methods:  [GET, DELETE, POST]